name: web_restaurant
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  autoequal: ^0.5.1
  bloc: ^8.1.2
  copy_with_extension: ^5.0.4
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flex_color_scheme: ^7.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^11.1.1
  go_router_paths: ^0.2.0
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2

dev_dependencies:
  autoequal_gen: ^0.5.1
  build_runner: ^2.3.3
  copy_with_extension_gen: ^5.0.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
